name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5"

      - name: Install dependencies
        run: opam install alcotest ocamlformat.0.25.1 --yes

      - name: Format check
        run: opam exec -- dune build @fmt

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune test
